travis:
  secure:
    BINSTAR_TOKEN: EGF7bcdRpHkNlHDPKL2PKjOduqiq/Wip/Y06rF+8taQ4tiH5Tj3yZtGR0y33obqOVp7loXlmIglNkUmokYeT3d4z0GEUi8egzt2ID2iRKbPJ0YOzY6Hqj6mgrS5YaKpv3ZHjFmIzwAAK/WuxwZstlNHFI7mTQSu2HzEOrWkw5wLxDNW0CIUV6Fp8JX65mUTpFcGxS8GKmC58SpI9XQA7Gnqen/OUMfH90a1994GrZkwsNsivKKwKg5Lft8E6PkvUfQUxnmIpqwlLBdyLdp/Ie7OARsGVe3PNR1/pEglXVcRflwIdYFZRm2MOQ09aPLYnPW+S357wjpn2y2yfD86kVDOSwEoJYdKZR3Uj1R9BzOnrwbXOTTE0sMBkN7Absha+SPWNQRP8Myoq3XJLylYj/BhpPESsUMa8oHqGOeqekUmJh7OWWgcDopkLRY3irhbG+ZhDxIiocLP+VS7YxnAJTpqaNQpzWSM81tOrhWmJ06ho3Vk6vdo7hOoJAN6iV3DXfNd7xPXYpwDZIkAucYqhmwfMcUyrH5TANLFP8Gr62qMY2dAq4KHpIG85NDQXmhpUY35KFjXuIoI83DhFdBfrRs6WC/ICFbJ7ecF8ZgUOdUbMyuXnQBqIaC/J1VpRdfhclI4DA8rr6d6uE77h1E1EC0063uxx6DT3HxLEUTggWys=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
