appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZHuY3hrwrxhSKSjsdSoN0QOJRwT69ihR93LCvGCchyGlZ+675mHLcJySRnbTYmtrEiNaedBWqFU0JfBoxjXJv1MJqPalIEAQTTXXKiqu3QXXGJYQ10LG4YTEfqqPE+41A4xhB/4a1yzvJGBdekevU46ap4Nkjt42wHpnQ2wR68x5yQZTHFAi1FGWq29MkANXHkJea9aI8U3ggrIB7z6mv4HccqlJsKVVahptRks382vTbZ/EUM4+4wTRIfyH8BdMr7qIxz1fUKwvmTxVNFlGW3FgRHAPBFWXnZ+m2z7rKboRd5TbVGIrW3mPcAMNgFre9fauzow4o2Q5dTD56Qvazdad3tnxNcaqad/8gW8u5am+LAYEj73QvEtCVulKH1Ze1Kdbuk8AqYb7npDrkp2BZ7Gef7dSrG1+36POOL8K8SIDKW1TG9X4eZNBZ+u8x9e9CRDNqwtUjbNypMGHXhIhpuRXl8MlpO5jHcVMBlSYcUQnpM17KCBfPhpkuv6VsqMPN2iJ+bToPDrcQK5o/+wmyln2o4fCg18LVjkNMGr5Jbt+tHXtKC3qFQuF6EIq+VBCRx4B3INU+QyBHIQjOConXOEbBMCnOQiDx9WfqRPwMvcWO3yAwplYXf5jp2iSTvU0zfEWW0zA3Zm4drY1GVvLbzI5VOyKxBoDOIBOlR+KgqE=}
bot:
  automerge: true
